name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  ce-dat:
    name: Build ce.dat
    uses: ./.github/workflows/reusable-build-ce-dat.yml
    with:
      preset: linux-x64-debug

  ios:
    name: iOS

    runs-on: macos-14
    needs: [ce-dat]

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: out
          key: ios-cmake-v102-release

      - name: Configure
        run: |
          cmake --preset ios

      - name: Build
        run: |
          cmake --build --preset ios-release

      - name: Pack
        run: |
          cd out/build/ios
          cpack -C RelWithDebInfo

      - name: Download ce.dat
        uses: actions/download-artifact@v4
        with:
          name: ce-dat
          path: out/dist

      - name: Package
        run: |
          mkdir -p out/dist/fallout2-ce-ios
          cp out/build/ios/fallout2-ce.ipa out/dist/fallout2-ce-ios/fallout2-ce-ios.ipa
          cp out/dist/ce.dat out/dist/fallout2-ce-ios/ce.dat
          cp files/fallout2.cfg out/dist/fallout2-ce-ios/EXAMPLE_fallout2.cfg
          cd out/dist
          zip -r fallout2-ce-ios.zip fallout2-ce-ios

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fallout2-ce-ios
          path: out/dist/fallout2-ce-ios.zip
          retention-days: 7
